[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
access_control = "ExUZnBBEJKDi7DiyktBiET6M3ksX7qpGwyp4gVQZ9h8u"
accountant = "Hs5EYj3jcBr2bishRa4Cjk39iDm9sLbQ1TyCToSTGLSS"
deposit_limit = "Dj9DcwRzLK9yXz5xdAeRFmp2EjpFYZ3En5N8ApfxpCfU"
faucet = "C3dz2V23uqX5br1rdA2xmahNVMPribqCLPU9NYxrA71t"
strategy_program = "EDA9ee5UKzdqrHgSd5v64bNnbCae1t7NJfUpvS7DZod"
tokenized_vault = "BSDXNWPssxYs1A1KBUFMj9KykVWsJRaHYNfRwSqijYwv"

[programs.localnet]
access_control = "ExUZnBBEJKDi7DiyktBiET6M3ksX7qpGwyp4gVQZ9h8u"
accountant = "Hs5EYj3jcBr2bishRa4Cjk39iDm9sLbQ1TyCToSTGLSS"
deposit_limit = "Dj9DcwRzLK9yXz5xdAeRFmp2EjpFYZ3En5N8ApfxpCfU"
faucet = "C3dz2V23uqX5br1rdA2xmahNVMPribqCLPU9NYxrA71t"
strategy_program = "EDA9ee5UKzdqrHgSd5v64bNnbCae1t7NJfUpvS7DZod"
tokenized_vault = "BSDXNWPssxYs1A1KBUFMj9KykVWsJRaHYNfRwSqijYwv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
demo = "yarn run demo"
dev_test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/integration/vault.ts"
init_faucet = "yarn run init_faucet"
init_trade_fi = "yarn run init_trade_fi"
init_vault = "yarn run init_vault"
initialize = "yarn run initialize"
process_report = "yarn run process_report"
set_roles = "yarn run set_roles"
shutdown_vault = "yarn run shutdown_vault"
test = "yarn run ts-mocha -r dotenv/config -p ./tsconfig.json -t 2000000 --require './tests/integration/setups/globalSetup.ts' --recursive 'tests/integration/**/*.test.ts'"
underlying_mint = "yarn run underlying_mint"
update_deposit_limit = "yarn run update-deposit-limit"
whitelist = "yarn run whitelist"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "mpl_token_metadata.so"
