[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
strategy_program = "ErJGueTn3xVKETP4dc8vrmS5Lu7iupJZ2pr7kYJkCtUE"
tokenized_vault = "CNyqz3mqw6koNmAe7rn2xHGHAS9ftXUNQohwHSiXhJLQ"
faucet = "GUrM139EUwYkoEWebecqiTLJrvut4mDdHGTu9d87tgQC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.solana.splyce.finance"
wallet = "~/.config/solana/id.json"

[scripts]
demo = "yarn run demo"
init_vault = "yarn run init_vault"
set_roles = "yarn run set_roles"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/integration/**/*.ts"
whitelist = "yarn run whitelist"
update_deposit_limit = "yarn run update-deposit-limit"
init_faucet = "yarn run init_faucet"
process_report = "yarn run process_report"
init_trade_fi =  "yarn run init_trade_fi"

[[test.genesis]] 
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" 
program = "mpl_token_metadata.so"