[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
access_control = "G4R4QqWTLGoNCs1DRFpSHxPAJohe5obP8n8RVrHBMH33"
accountant = "FUtRzVSpo1cEjEGPzbowQj3vdcEoUJfvTKbn8mw8ZKSS"
deposit_limit = "5ftd8XcvMXHFquqBFKP7BgdzLnxPodtnoowB3GKn5528"
faucet = "sZyuAVwfJvgcopZtHq5y5wQ488qaWkSqdX1xPKsTYeX"
strategy_program = "EDA9ee5UKzdqrHgSd5v64bNnbCae1t7NJfUpvS7DZod"
tokenized_vault = "8Y5ZEEnhiNdvGHbfiZVj2eSawrNrQTKd9jPEFqnnKizC"

[programs.localnet]
access_control = "G4R4QqWTLGoNCs1DRFpSHxPAJohe5obP8n8RVrHBMH33"
accountant = "FUtRzVSpo1cEjEGPzbowQj3vdcEoUJfvTKbn8mw8ZKSS"
deposit_limit = "5ftd8XcvMXHFquqBFKP7BgdzLnxPodtnoowB3GKn5528"
faucet = "sZyuAVwfJvgcopZtHq5y5wQ488qaWkSqdX1xPKsTYeX"
strategy_program = "EDA9ee5UKzdqrHgSd5v64bNnbCae1t7NJfUpvS7DZod"
tokenized_vault = "8Y5ZEEnhiNdvGHbfiZVj2eSawrNrQTKd9jPEFqnnKizC"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/mainnet.json"

[scripts]
demo = "yarn run demo"
dev_test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/integration/vault.ts"
init_faucet = "yarn run init_faucet"
init_trade_fi = "yarn run init_trade_fi"
init_vault = "yarn run init_vault"
initialize = "yarn run initialize"
process_report = "yarn run process_report"
set_roles = "yarn run set_roles"
shutdown_vault = "yarn run shutdown_vault"
test = "yarn run ts-mocha -r dotenv/config -p ./tsconfig.json -t 2000000 --require './tests/integration/setups/globalSetup.ts' --recursive 'tests/integration/**/*.test.ts'"
underlying_mint = "yarn run underlying_mint"
update_deposit_limit = "yarn run update-deposit-limit"
whitelist = "yarn run whitelist"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "mpl_token_metadata.so"
