[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
access_control = "J52o5B6RAEJVWktG4aWnocHEVvDDfmbgnnbXqHAGsk6n"
accountant = "ETcQrVkt8V3BgZnD7vvKjDoiDHoEdRuDgeEx9Zg3hb7q"
deposit_limit = "B3o9MgocmVyMQM7Y3DQCAhk1xAA8kH5KmBdsF2fak9yd"
faucet = "DuEQqHmtzWJSH83WocsY5pBRRJsaqwMoX6bzC6HsWWDP"
strategy_program = "EDA9ee5UKzdqrHgSd5v64bNnbCae1t7NJfUpvS7DZod"
tokenized_vault = "3jjSmKtgz1fgfRp4PfiYM1TAkD2rLaAJSSMw2h7gpZs6"

[programs.localnet]
access_control = "J52o5B6RAEJVWktG4aWnocHEVvDDfmbgnnbXqHAGsk6n"
accountant = "ETcQrVkt8V3BgZnD7vvKjDoiDHoEdRuDgeEx9Zg3hb7q"
deposit_limit = "B3o9MgocmVyMQM7Y3DQCAhk1xAA8kH5KmBdsF2fak9yd"
faucet = "DuEQqHmtzWJSH83WocsY5pBRRJsaqwMoX6bzC6HsWWDP"
strategy_program = "EDA9ee5UKzdqrHgSd5v64bNnbCae1t7NJfUpvS7DZod"
tokenized_vault = "3jjSmKtgz1fgfRp4PfiYM1TAkD2rLaAJSSMw2h7gpZs6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
demo = "yarn run demo"
dev_test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/integration/vault.ts"
init_faucet = "yarn run init_faucet"
init_trade_fi = "yarn run init_trade_fi"
init_vault = "yarn run init_vault"
initialize = "yarn run initialize"
process_report = "yarn run process_report"
set_roles = "yarn run set_roles"
shutdown_vault = "yarn run shutdown_vault"
test = "yarn run ts-mocha -r dotenv/config -p ./tsconfig.json -t 2000000 --require './tests/integration/setups/globalSetup.ts' --recursive --reporter mocha-qase-reporter 'tests/integration/**/*.test.ts'"
underlying_mint = "yarn run underlying_mint"
update_deposit_limit = "yarn run update-deposit-limit"
whitelist = "yarn run whitelist"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "mpl_token_metadata.so"
