[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
strategy_program = "ErJGueTn3xVKETP4dc8vrmS5Lu7iupJZ2pr7kYJkCtUE"
tokenized_vault = "CNyqz3mqw6koNmAe7rn2xHGHAS9ftXUNQohwHSiXhJLQ"
faucet = "BnjdeSt6reRowzTYp5KQFWXnqBymUe4oNRwjfBW3g5Bu"

[programs.mainnet]
strategy_program = "FeMChq4ZCFP8UstbyHnVyme3ATa2vtteLNCwms4jLMAj"
tokenized_vault = "Crf2XbpWt5uLe7fJCohFrZYLXYu5asFh9QmHwjhreQQZ"
faucet = "4rza9AifAapN4SKho3teAuLhc1TPpNWp9DHNPEMzVqgp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/mainnet.json"

[scripts]
demo = "yarn run demo"
init_vault = "yarn run init_vault"
set_roles = "yarn run set_roles"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/integration/**/*.ts"
whitelist = "yarn run whitelist"
update_deposit_limit = "yarn run update-deposit-limit"
init_faucet = "yarn run init_faucet"
process_report = "yarn run process_report"
init_trade_fi =  "yarn run init_trade_fi"
underlying_mint = "yarn run underlying_mint"

[[test.genesis]] 
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" 
program = "mpl_token_metadata.so"