[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
strategy_program = "EDA9ee5UKzdqrHgSd5v64bNnbCae1t7NJfUpvS7DZod"
tokenized_vault = "8eDcyX8Z8yZXBQsuatwxDC1qzGbuUbP7wGERDBQoPmBH"
accountant = "49pfysnCNyz6HrKsTUaKtyp8DPcXQadjkS5qBJPJKEnJ"
faucet = "GUrM139EUwYkoEWebecqiTLJrvut4mDdHGTu9d87tgQC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
demo = "yarn run demo"
init_vault = "yarn run init_vault"
set_roles = "yarn run set_roles"
whitelist = "yarn run whitelist"
update_deposit_limit = "yarn run update-deposit-limit"
init_faucet = "yarn run init_faucet"
process_report = "yarn run process_report"
init_trade_fi =  "yarn run init_trade_fi"
underlying_mint = "yarn run underlying_mint"
initialize = "yarn run initialize"
test = "yarn run ts-mocha -r dotenv/config -p ./tsconfig.json -t 2000000 --require './tests/integration/setups/globalSetup.ts' --recursive --reporter mocha-qase-reporter 'tests/integration/**/*.test.ts'"
dev_test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/integration/vault.ts"

[[test.genesis]] 
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" 
program = "mpl_token_metadata.so"

[test]
startup_wait = 10000