[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
strategy_program = "EDA9ee5UKzdqrHgSd5v64bNnbCae1t7NJfUpvS7DZod"
tokenized_vault = "8eDcyX8Z8yZXBQsuatwxDC1qzGbuUbP7wGERDBQoPmBH"
faucet = "GUrM139EUwYkoEWebecqiTLJrvut4mDdHGTu9d87tgQC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 2000000 --require './tests/integration/setups/globalSetup.ts' --recursive 'tests/integration/**/*.test.ts'"
dev_test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/integration/**/*.ts"
set_roles = "yarn run set_roles"
init_vault = "yarn run init_vault"
whitelist = "yarn run whitelist"
init_faucet = "yarn run init_faucet"

[[test.genesis]] 
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" 
program = "mpl_token_metadata.so"
